### ISSUE TITLE
Dark font on dark panel background

### ISSUE THREAD

**Issue by tyeporter** [SublimeText/Theme-DAneo#11]
Thank you for this awesome theme! I'm loving it as I'm using ST as my primary editor.

Is there a way to change the font color within the output panel so that the font contrasts its background? 

<img width="869" alt="Screen Shot 2020-10-25 at 6 34 58 PM" src="https://user-images.githubusercontent.com/16263420/97122097-30684000-16f1-11eb-88b0-28d4b6d9fe75.png">

**Comment by deathaxe** [comment]
Looks related with the syntax assigned to the build system and/or the color-scheme highlighting the output in that color.

Build system output is assigned _Plain Text.tmLanguage_ by default which renderes the output with normal text color. Should be the same as the statusbar color normally.

**Comment by tyeporter** [comment]
After removing [Theme - Legacy](https://packagecontrol.io/packages/Theme%20-%20Legacy) my plain text went back to normal. I think it had something to do with my package cache files. 

Anyway, thanks for your response! I'll go ahead and close this issue.
