### ISSUE TITLE
Help with quick panel - cannot see input text box

### ISSUE THREAD

**Issue by cfc-librarian** [SublimeText/Theme-DAneo#12]
Any help with this much appreciated:

Recently shifted laptops to one with a 1366x768 screen.  The dpi is set correctly, and all other applications are working fine.  With sublimetext 3 and the daneo sodaish theme the quick panel text input box is obstructed by the buttons when set to half screen, which is how I use it 90% of the time.  A screenshot is attached.

Thank you also for resurrecting the DA theme.  I've been using it for years now, but decided to make a switch with the computer change.
![Screenshot_2021-01-14_16-03-54](https://user-images.githubusercontent.com/46627215/104649511-c1293900-56ac-11eb-88ea-2c07478a95f3.png)

**Comment by deathaxe** [comment]
It appears even if icon buttons on the left and the buttons on the right would be as small as possible, it wouldn't give you rasonable space for input fields. With your screen resolution the window should be about 680px wide. I tried the same on Windows with following result.

![grafik](https://user-images.githubusercontent.com/16542113/104737222-46136180-5744-11eb-9ac9-a3c34e2f39d3.png)

Situation doesn't change much with Adaptive.sublime-theme, which is shipped with ST out of the box.

![grafik](https://user-images.githubusercontent.com/16542113/104737358-6cd19800-5744-11eb-9093-89c00d545769.png)

Have you tried to set `"ui_scale: 0.7"` to reduce size of UI elements?

**Comment by cfc-librarian** [comment]
Thank you.

It seems like this is an issue with the rendering of the Sublime Text 3 application under Arch Linux/i3wm.  Using the sublime preference "ui_scale: 1.1" allows the quick panel to be used when a sublime project is opened "half screen".  This is a big help!

![Screenshot_2021-01-15_10-01-11](https://user-images.githubusercontent.com/46627215/104742872-e4062c80-5742-11eb-8b3f-22f65b6a701a.png)

While the HIDPI "fixes" and "changes" are good for large screens and newer hardware, they really wreak havoc with those of us using simpler equipment. 

The sublime menu is still unreasonably large - but a package "hide menu" takes care of that.  Now the status is tough to read, but I can modify the custom status font, so that shouldn't be too hard.

One small question - is there any way to reduce the spacing between items on the file list? :+1: 

![Screenshot_2021-01-15_10-10-34](https://user-images.githubusercontent.com/46627215/104743418-95a55d80-5743-11eb-963e-ed7830487225.png)

**Comment by deathaxe** [comment]
Title bar and main menu are native gtk controls and afaik not under direct control of ST with regards to style and size. Also your pdf viewer's controls look quite large. I am not a linux expert, but my impression is a global scaling factor to be applied.

By explicitly setting `ui_scale` those global OS values are overriden for client controls.
