### ISSUE TITLE
No indication when folder is git-ignored

### ISSUE THREAD

**Issue by rchl** [SublimeText/Theme-DAneo#15]
Not sure if it has never worked or it broke at some point...

This is default theme:

![Screenshot 2021-04-06 at 13 05 35](https://user-images.githubusercontent.com/153197/113701702-c957aa00-96d8-11eb-9b18-26f288e8b006.png)

This is DAneo:

![Screenshot 2021-04-06 at 13 07 03](https://user-images.githubusercontent.com/153197/113701861-fd32cf80-96d8-11eb-9a8d-9ed4b32a052b.png)

Both `dist` and `node_modules` are git-ignored but this theme doesn't indicate that.

**Comment by deathaxe** [comment]
I commented out rules for `untracked` and `ignored` folders as I had an issue with all folders containing at least one untracked file being greyed out and thus looking like being ignored. I guess I was under the impression that applies for both states, which seems wrong.

Folders containing ignored files (but no untracked not ignored ones), don't receive any special state while those with at least one untracked but not ignored file are marked `untracked`.

**Comment by rchl** [comment]
Are you planning a new release with this fix soon? :)
