### ISSUE TITLE
Sublime Text 4 now throwing package incompatible

### ISSUE THREAD

**Issue by ciscohack** [SublimeText/Theme-DAneo#16]
Hi Team,

could you please fix the issue sublime text 4 now complaining this version is incompatible. i using this since very log and love it. i don't wanna delete. please fix the package compatibility issue.

**Comment by deathaxe** [comment]
That's a general Package Control issue. It throws this error but should install correct version at the same time (with some luck).

If not, you may want to uninstall and reinstall to get the correct version for ST4.

**Comment by ciscohack** [comment]
Thanks for quick response. i will try this then. Thanks for amazing theme
