### ISSUE TITLE
New UI element in 4131 that needs styling

### ISSUE THREAD

**Issue by rchl** [SublimeText/Theme-DAneo#17]
Modal dialogs without "title bar" (like the native project switcher below) now have a cancel button on macOS that looks unstyled:

![Screenshot 2022-03-25 at 10 55 12](https://user-images.githubusercontent.com/153197/160100825-6b1164cb-bcad-41eb-9356-8b3a13120494.png)

**Comment by deathaxe** [comment]
I've pushed some changes to master. Would you mind trying them out? I have no MacOS to test anything.

**Comment by rchl** [comment]
I think it's looking good:

![Screenshot 2022-03-25 at 20 38 03](https://user-images.githubusercontent.com/153197/160189904-89681b13-1ebe-43ee-b9ed-597a4943cc43.png)

For comparison this is how it looks in default theme:

![Screenshot 2022-03-25 at 20 37 43](https://user-images.githubusercontent.com/153197/160189969-06fe59ad-3913-49ef-97fe-1a7580be161f.png)

**Comment by deathaxe** [comment]
I think way should add some more space so the button doesn't touch the round window border.

**Comment by rchl** [comment]
Looks like this now:

![Screenshot 2022-03-29 at 11 42 37](https://user-images.githubusercontent.com/153197/160583207-0d7a53cc-09f7-4ce9-8098-c0079271ac9d.png)


I'm still happy with it but someone could argue that the button should have even margin on either side (also on top).
I'm not that picky though.
