### ISSUE TITLE
Status bar size

### ISSUE THREAD

**Issue by nero-0** [SublimeText/Theme-DAneo#5]
Hi all. 

First of all, I would like to thank you for bringing us this beautiful theme. So going straight to the point, is there any chance that a setting to control the size of the status bar will be added? It looks a little big on my screen, so making it a little flatter would be great. 😃 

Thanks for reading!

**Comment by deathaxe** [comment]
If you have PackageDev installed, you could _Edit Current Theme_ via command palette and add the following content to the overriding user file to reduce the size of the status bar.

Please note: the content_margin's format is: `[<left>, <top>, <right>, <bottom>]` 

```
{
    // http://www.sublimetext.com/docs/3/themes.html
    "variables": {
        // "font_face": "system",
    },
    "rules": [
        {
            "class": "status_bar",
            "content_margin": [10, 2, 0, 2]
        },
        {
            "class": "status_button",
            "content_margin": [10, 0, 10, 0]
        },
   ],
}
```

**Comment by nero-0** [comment]
Thanks! I did that and it looks much better now. 😄 
Are there rules for doing that with the find and tabs bar too?

**Comment by deathaxe** [comment]
Of course. You could basically write override rules for literly any control. It's just a bit tricky as there are several settings which depend on each other and need to be adjusted carefully to make the UI look well. It's easy to break things - especially if multiple layers of textures are used to design a control.

Unfortunatelly the theme engine doesn't allow math operations to adjust such things depending on a single integer user setting.

**Comment by nero-0** [comment]
I see. Could you guide me through these two areas (find and tabs bar)? If it's a lot of work, you can just tell me which settings depend on them to make everything look well, from that I can try to deal with the rest. 

Also, I've noticed that it's possible to increase the size of the find bar by dragging it, but not decrease it. Perhaps by the size of the icons?

In any case, thanks a lot for your help so far! 😄

**Comment by deathaxe** [comment]
Maybe the easiest way was to checkout the current master branch and set `"tabset_size_small": true` in the Preferences.sublime-settings to enable slightly smaller tabs - added today. Hope I found a good balance.

**Comment by nero-0** [comment]
Thanks! But I didn't notice any difference when setting `"tabset_size_small": true` in preferences.
There is also no update when checking the package control.

**Comment by deathaxe** [comment]
It's not yet released via package control - only pushed to Github.

**Comment by nero-0** [comment]
Alright, I'll keep an eye out and when I'm ready I'll give you some feedback. 

Regards.

**Comment by nero-0** [comment]
I read a little bit about how the structure of the themes works in ST3, and I managed to leave things better on my side. So I'm closing this issue.

Regards.
