### ISSUE TITLE
Inconsistent quick panel padding

### ISSUE THREAD

**Issue by rchl** [SublimeText/Theme-DAneo#6]
v0.4.2

This is the new Quick Panel in ST4:

![Screenshot 2020-08-28 at 14 23 56](https://user-images.githubusercontent.com/153197/91560404-1cdf6980-e93a-11ea-88fe-df1acfe7c4fa.png)

This is the native "go to symbol" quick panel:

![Screenshot 2020-08-28 at 14 25 08](https://user-images.githubusercontent.com/153197/91560529-47312700-e93a-11ea-984b-967d88e03501.png)

**Comment by rchl** [comment]
And new Quick Panel without `detail` field:

![Screenshot 2020-08-28 at 14 29 25](https://user-images.githubusercontent.com/153197/91560928-f5d56780-e93a-11ea-9270-b6b69cf6a971.png)

**Comment by deathaxe** [comment]
Selectors have changed. Already prepared a fix, but ran into some other issues with QuickPanelItems which I wanted to fix before publishing.

**Comment by deathaxe** [comment]
Should be fixed in v0.4.4

**Comment by rchl** [comment]
Is looking good now. Thanks.
