### ISSUE TITLE
Titlebar and tab bar not quite right on Mac with Solarized

### ISSUE THREAD

**Issue by jeffcox** [SublimeText/Theme-DAneo#9]
Tried with multiple themes, this only seems to happen with the color schemes from the "Solarized Color Scheme" package.

Glad to see DA back, thanks for all your work!

<img width="1453" alt="Screen Shot 2020-10-19 at 2 43 07 PM" src="https://user-images.githubusercontent.com/200446/96515232-d6abd580-1219-11eb-90ed-4aadf3461411.png">

**Comment by deathaxe** [comment]
Thank's for reporting.

The title bar should have the same color as the sidebar (and tabset) as of version 0.4.6
